### ISSUE TITLE
App crashed when i clicked on idol

### ISSUE THREAD

**Issue by cckole** [pnthach95/LLSIFTomodachiApp#7]
### Descriptions

When I launched the app and clicked on idol, the app crashed. This happens while data connection was off. However, it keeps loading anytime I'm connected and click on it.

### Steps to reproduce
 
Launch the app without data connection

- click on idol
- note the crash.

You can also switch data on and click on it again. It will keep loading without any display.

### Expected behavior

My expectation was to see it load and display the images of the idols.

### Reproducing the bug

![20190709_115659](https://user-images.githubusercontent.com/36272218/60883140-4bcfe300-a241-11e9-9e1d-6d593da33e64.gif)

### Device used

Tekno spark k7

Android 7.0

App version

**Comment by pnthach95** [comment]
Thank for your report. I had seen some bug reports and wondered what happened. It don't have check data connection function, so app crashes. I will add this. About idols tab, I don't know. I will check later.

**Comment by pnthach95** [comment]
https://github.com/MagiCircles/SchoolIdolAPI/issues/339

**Comment by pnthach95** [comment]
[Released new version.](https://github.com/pnthach95/LLSIFTomodachiApp/releases/tag/0.3.0) It fixed the bugs.
